Repository bluerobotics/BlueOS, pull requests merged in 2023-09, with the labels that each got.

#2080 core: frontend: src: types: kraken: add `tool`
  core/frontend/src/types/kraken.ts
Labels: docs-complete

#2022 install: Check for rfkill before running it
  install/install.sh
Labels: merge-after-stable

#1958 core: services: wifi: wpa_supplicant: Try to reconnect socket if it fails
  core/services/wifi/wpa_supplicant.py
Labels: merge-after-stable

#2031 Major Tom 2: A missão
  core/services/install-services.sh
  core/services/major_tom/main.py
  core/services/major_tom/setup.py
  core/services/major_tom/src/__init__.py
  core/services/major_tom/src/core.py
  core/services/major_tom/src/metrics.py
  core/services/major_tom/src/typedefs.py
  core/start-blueos-core
Labels: docs-needed
